name: Deploy Preview

on:
  workflow_run:
    workflows: ["Build Preview", "Test"]
    types:
      - completed

jobs:
  deploy-preview:
    runs-on: ubuntu-latest
    if: ${{github.event.workflow_run.event == 'pull_request' && github.event.workflow_run.conclusion == 'success'}}
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install --global netlify-cli@6
      - run: npm install unzipper@0.10 request@2.88.2
      - uses: actions/github-script@v5
        with:
          script: |
            const unzipper = require('unzipper');
            const request = require('request');

            const artifacts = github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id}},
            });

            console.log('artifacts', artifacts);

            const artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == 'pr';
            })[0];

            const directory = await unzipper.Open.url(request, artifact['archive_download_url']);
            const file = directory.files.find(d => d.path === 'number');
            const content = await file.buffer();
            const number = parseInt(content.toString(), 10);

            console.log('pr number', number);

  test-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install --global netlify-cli@6 unzipper@0.10
      - name: Get pull request number
        uses: actions/github-script@v5
        with:
          script: |
            const unzipper = require('unzipper');

            const artifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: ${{github.event.workflow_run.id}},
            });

            const artifact = artifacts.data.artifacts.filter((artifact) => {
              return artifact.name == 'pr';
            })[0];

            if (!artifact) {
              throw new Error('No pr artifact found');
            }

            const download = await github.rest.actions.downloadArtifact({
              owner: context.repo.owner,
              repo: context.repo.repo,
              artifact_id: artifact.id,
              archive_format: 'zip',
            });

            const directory = await unzipper.Open.buffer(Buffer.from(download.data));
            const file = directory.files.find(d => d.path === 'number');
            const content = await file.buffer();
            const number = parseInt(content.toString(), 10);

            console.log('pr number', number);
