name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CI: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm test
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build-site
      - uses: actions/upload-artifact@v2
        with:
          name: site
          path: build/site
      - run: |
          mkdir -p build/pr
          echo '42' > build/pr/number
      - uses: actions/upload-artifact@v2
        with:
          name: pr
          path: build/pr